### ISSUE TITLE
MessageProvider should have two independent StoreADUs objects for sending(insert) and receiving(query) ADUs

### ISSUE THREAD

**Issue by JAReddy** [SJSU-CS-systems-group/DDD#147]
**Describe the bug**
Currently, the MessageProvider has only one StoreADUs object and it is initialized only to be used for inserting ADUs. Query fetches the ADUs from the same StoreADUs and which uses the wrong directory to fetch the received ADUs.

**Expected behavior**
The MessageProvider class has two objects of StoreADUs class and onCreate should initialize both for sending and receiving based on the boolean argument. Appropriate object should be used for insert and query methods.

**Comment by priyamtated101** [comment]
https://github.com/SJSU-CS-systems-group/DDD/pull/165
