### ISSUE TITLE
Add storage limits and storage cleanup fuction to BundleTransport

### ISSUE THREAD

**Issue by breed** [SJSU-CS-systems-group/DDD#281]
We need to add a storage management fragment to BundleTransport that:

1) limits the amount of storage used by BundleTransport to a user selectable value. Auto delete older files if the limit is hit.
2) allows the user to free up a given amount of storage by deleting older files.

**Comment by 03fernanda-palacios** [comment]
Solved with PR https://github.com/SJSU-CS-systems-group/DDD/pull/335Solved with PR https://github.com/SJSU-CS-systems-group/DDD/pull/335
