### ISSUE TITLE
unify packaging around discdd.net

### ISSUE THREAD

**Issue by breed** [SJSU-CS-systems-group/DDD#88]
we have a variety of packages being used, none of which are domains that belong to us. i have reserved discdd.net. we need to unify around that domain.

this is going to be an extremely disruptive change. we need to coordinate it well. perhaps with a rename day or something.

**Comment by breed** [comment]
we should also pick real names for our activity classes. HelloWorld is not a good name :)

**Comment by Innominate-Majesty** [comment]
Needed to complete:

BundleCore (currently it might affect others so we can change it later)
